package cmd

import (
	"context"
	"fmt"
	"os"

	"github.com/spf13/cobra"

	"github.com/gbrindisi/littlebox/internal/container"
)

var (
	forceTTY bool
	noTTY    bool
	rebuild  bool
	debug    bool
	labels   []string
	name     string
)

var runCmd = &cobra.Command{
	Use:          "run [-- agent-args]",
	Short:        "Run an agent in an isolated container",
	SilenceUsage: true,
	Long: `Run an agent in an isolated Docker container with network and filesystem isolation.

The run command loads configuration from an Agentfile (or specified config file),
builds the littlebox image if not cached, creates a container with the configured
security settings, and attaches to it.

Arguments after -- are passed directly to the agent command.

Examples:
  # Run with default Agentfile in current directory
  littlebox run

  # Run with a specific config file
  littlebox run -c /path/to/Agentfile

  # Override workspace directory
  littlebox run -w /path/to/workspace

  # Name and label the container (littlebox=1 is always added)
  littlebox run --name my-agent --label team=infra --label task=42

  # Pass arguments to the agent
  littlebox run -- --help`,
	RunE: func(cmd *cobra.Command, args []string) error {
		// Check for mutually exclusive flags
		if forceTTY && noTTY {
			return fmt.Errorf("--tty and --no-tty are mutually exclusive")
		}

		// Validate container metadata flags before doing any work
		parsedLabels, err := container.ParseLabels(labels)
		if err != nil {
			return err
		}
		if err := container.ValidateContainerName(name); err != nil {
			return err
		}

		// Load and validate configuration
		cfg, err := loadAndValidateConfig()
		if err != nil {
			return err
		}

		// Determine TTY mode from flags
		var ttyMode container.TTYMode
		if forceTTY {
			ttyMode = container.TTYForce
		} else if noTTY {
			ttyMode = container.TTYNone
		} else {
			ttyMode = container.TTYAuto
		}

		exitCode, err := runContainer(context.Background(), runOptions{
			cfg:     cfg,
			args:    args,
			ttyMode: ttyMode,
			rebuild: rebuild,
			debug:   debug,
			create:  container.CreateOptions{Name: name, Labels: parsedLabels},
		})
		if err != nil {
			return err
		}
		// Exit with container's exit code to propagate it to the shell
		os.Exit(exitCode)
		return nil // unreachable: required by function signature
	},
}

func init() {
	runCmd.Flags().BoolVar(&forceTTY, "tty", false, "force TTY allocation")
	runCmd.Flags().BoolVar(&noTTY, "no-tty", false, "disable TTY allocation")
	runCmd.Flags().BoolVar(&rebuild, "rebuild", false, "force rebuild of derived image even if cached")
	runCmd.Flags().BoolVar(&debug, "debug", false, "enable debug output with verbose logs")
	runCmd.Flags().StringArrayVar(&labels, "label", nil, "set a container label as key=value (repeatable)")
	runCmd.Flags().StringVar(&name, "name", "", "container name (default: generated by Docker)")
	rootCmd.AddCommand(runCmd)
}
